name: windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:  # manual start

permissions:
    contents: read

jobs:
  build:

    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}

    steps:
    - uses: actions/checkout@v4
    - uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: false
        install: git make mingw-w64-x86_64-toolchain mingw-w64-x86_64-zlib
    - name: Build project
      run: make TARGETOS=windows32
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: windows-build
        path: ./build/*.exe  # path
